<!DOCTYPE html>

<html>

<head>

<style>

body{
    font-family: DejaVu Sans, sans-serif;
    font-size:12px;
    line-height:1.5;
}


h1{
    text-align:center;
    font-size:22px;
}


h3{
    margin-top:20px;
}


h2{
    border-bottom:1px solid #333;
    padding-bottom:5px;
    margin-top:20px;
}


.page-break{
    page-break-after:always;
}


table{
    width:100%;
    border-collapse:collapse;
}


td,th{
    border:1px solid #ccc;
    padding:8px;
}


.badge{

font-size:10px;

}


</style>


</head>


<body>


<h1>
ALGOSPACE CYBER & TECH SERVICES
</h1>


<h3 style="text-align:center">
COURSE HANDBOOK
</h3>


<hr>


<h2>
{{ $course->name }}
</h2>




@if($course->outline)


<h2>
1. Course Overview
</h2>


<p>
{{ $course->outline->overview }}
</p>




<h2>
2. Learning Objectives
</h2>



@foreach($course->outline->items->where('section','objective') as $item)


<h4>
{{ $item->title }}
</h4>


<p>
{{ $item->description }}
</p>


@endforeach





<h2>
3. Learning Outcomes
</h2>



@foreach($course->outline->items->where('section','outcome') as $item)


<p>

<strong>
✓ {{ $item->title }}
</strong>

<br>

{{ $item->description }}

</p>


@endforeach



@endif





<div class="page-break"></div>





<h2>
4. Course Sessions
</h2>




@if($course->sessions->count())


@foreach($course->sessions as $session)



<h3>

Session {{ $session->session_number }}

:
{{ $session->title }}

</h3>



<p>
{{ $session->description }}
</p>




<h4>
Topics
</h4>



@if($session->topics->count())


<ul>


@foreach($session->topics as $topic)


<li>

<strong>
{{ $topic->title }}
</strong>

<br>

{{ $topic->description }}

</li>


@endforeach


</ul>


@else


<p>
No topics assigned.
</p>


@endif





<h4>
Learning Materials
</h4>



<ul>



@foreach($course->materials->where('course_session_id',$session->id) as $material)


<li>


<strong>
{{ $material->title }}
</strong>


-
{{ ucfirst($material->type) }}


<br>


{{ $material->description }}


</li>


@endforeach



</ul>





@endforeach



@else


<p>
No sessions available.
</p>


@endif







<div class="page-break"></div>







<h2>
5. Course Resources
</h2>




@php

$generalMaterials =
$course->materials->whereNull('course_session_id');

@endphp





@if($generalMaterials->count())


<ul>


@foreach($generalMaterials as $material)


<li>


<strong>
{{ $material->title }}
</strong>


<br>


Type:
{{ ucfirst($material->type) }}


<br>


{{ $material->description }}



</li>


@endforeach


</ul>


@else


<p>
No general course resources available.
</p>


@endif








<h2>
6. Assessment
</h2>



@if($course->outline)



@foreach($course->outline->items->where('section','assessment') as $item)


<p>


<strong>
{{ $item->title }}
</strong>


<br>


{{ $item->description }}


</p>



@endforeach



@endif






<h2>
7. Certificate Information
</h2>




@if($course->outline)


<p>

{{ $course->outline->certificate_information }}

</p>


@endif






<h2>
8. Additional Notes
</h2>



@if($course->outline)


<p>

{{ $course->outline->notes }}

</p>


@endif




<hr>


<p style="text-align:center">

Generated by ALGOSPACE CYBER & TECH SERVICES

<br>

Digital & Tech Solutions

</p>



</body>

</html>